#bool(value)

print(bool())
print(bool([]))
print(bool(()))
print(bool(''))
print(bool(True))
print(bool(False))
print(bool(0))
print(bool(1))
print(bool('o'))
print(bool(['a value']))
print(bool('A String'))
print(bool(None))
print(bool(-9))